//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeSheet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokeSheet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilities Parsed.
        /// </summary>
        internal static string AbilityParsed {
            get {
                return ResourceManager.GetString("AbilityParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Pokémon has a capability that is not yet inside this program, sorry!.
        /// </summary>
        internal static string CapabilityError {
            get {
                return ResourceManager.GetString("CapabilityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capabilities Parsed.
        /// </summary>
        internal static string CapabilityParsed {
            get {
                return ResourceManager.GetString("CapabilityParsed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap imgNotFound {
            get {
                object obj = ResourceManager.GetObject("imgNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INI File|*.ini.
        /// </summary>
        internal static string IniFilter {
            get {
                return ResourceManager.GetString("IniFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move list successfully parsed!.
        /// </summary>
        internal static string MoveParsed {
            get {
                return ResourceManager.GetString("MoveParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0} file.
        /// </summary>
        internal static string OfdTitle {
            get {
                return ResourceManager.GetString("OfdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Pokemon File.
        /// </summary>
        internal static string OpenPokemonFile {
            get {
                return ResourceManager.GetString("OpenPokemonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse failed..
        /// </summary>
        internal static string ParseFailed {
            get {
                return ResourceManager.GetString("ParseFailed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Pokeball {
            get {
                object obj = ResourceManager.GetObject("Pokeball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Pokeball16 {
            get {
                object obj = ResourceManager.GetObject("Pokeball16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Pokeball32 {
            get {
                object obj = ResourceManager.GetObject("Pokeball32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Pokeball64 {
            get {
                object obj = ResourceManager.GetObject("Pokeball64", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon Parsed.
        /// </summary>
        internal static string PokemonParsed {
            get {
                return ResourceManager.GetString("PokemonParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Pokemon to file....
        /// </summary>
        internal static string SavePokemonToFile {
            get {
                return ResourceManager.GetString("SavePokemonToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File|*.txt.
        /// </summary>
        internal static string TextFileFilter {
            get {
                return ResourceManager.GetString("TextFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width: {0}, Height: {1}.
        /// </summary>
        internal static string WidthHeightFormat {
            get {
                return ResourceManager.GetString("WidthHeightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay..
        /// </summary>
        internal static string Yay {
            get {
                return ResourceManager.GetString("Yay", resourceCulture);
            }
        }
    }
}
